version: '3.3'

services:
  app:
    image: red-tetris-img
    container_name: red-tetris-container
    build:
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    volumes:
      - ./front:/app/front
      - ./server:/app/server
      - /app/front/build
      - /app/front/node_modules
      - /app/server/node_modules
    restart: always
