version: '3.3'

services:
  app:
    image: red-tetris-img
    container_name: red-tetris-container
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./front:/app/front
      - ./server:/app/server
      - /app/front/node_modules
      - /app/server/node_modules
    # env_file:
    #   - .env
    restart: always
