FROM node:latest

WORKDIR /front

COPY package.json package-lock.json ./

RUN npm config set registry https://registry.npmjs.org/ --timeout=120000
RUN npm install

EXPOSE 3000

CMD [ "npm", "run", "start" ]